### ISSUE TITLE
Redirect old docs to new docs

### ISSUE THREAD

**Issue by papb** [sequelize/website#100]
I think we should add a 301 REDIRECT (Moved Permanently) to the [old v3 docs](https://sequelize.readthedocs.io/en/v3/) and the ["old" v5 docs](http://docs.sequelizejs.com/) pointing to the new hosts instead ([here](https://sequelize.org/v3/) and [here](https://sequelize.org/master/) respectively).

This would solve sequelize/sequelize#10610 as well

@sushantdhiman

**Comment by sdepold** [comment]
I guess this ticket is done @ephys ?

**Comment by sdepold** [comment]
So this works now https://sequelize.readthedocs.io/en/v3/.

**Comment by ephys** [comment]
> I guess this ticket is done @ephys ?

Yep! Looks good :)
