### ISSUE TITLE
ForeignKey is not exported from sequelize as stated in the docs

### ISSUE THREAD

**Issue by Chigozie-Gerald** [sequelize/website#137]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

**Comment by ephys** [comment]
Which version of Sequelize are you using?
This sounds more like a typing issue than a docs issue

I'm pretty sure it's exported, it's used in our test here https://github.com/sequelize/sequelize/blob/v6/test/types/typescriptDocs/ModelInit.ts, so it's possible you're using a version of Sequelize that doesn't have it yet

**Comment by Chigozie-Gerald** [comment]
I am currently using version 6.18.0. 
Anyway, decided to update the npm package regardless and now it works. It is still on 6.18.0 anyway but I don't know why it worked.
Thanks a lot!
