### ISSUE TITLE
incorrect "changed" description

### ISSUE THREAD

**Issue by collierrgbsitisfise** [sequelize/website#189]
According this [doc](https://github.com/sequelize/website/blob/main/versioned_docs/version-6.x.x/other-topics/upgrade.md#modelchanged) instance.changed(), does not detect changes for jsonb fields, but it's a not TRUTH. According my check changes are successfully detected, cause under the hood [_.isEqual](https://lodash.com/docs/4.17.15#isEqual) is used, which works fine with nested object according lodash docs _"Performs a deep comparison between two values to determine if they are equivalent."_

**Comment by collierrgbsitisfise** [comment]
@ephys Yes, it's make more sense - will close this issue. Thanks !

**Comment by ephys** [comment]
I'll keep it open if you don't mind, as a reminder for us to update the website :)
