### ISSUE TITLE
A link leading to a deprecated(no longer existing) page

### ISSUE THREAD

**Issue by UponTheSky** [sequelize/website#343]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description
Although it could be deemed as minor, I report this issue for better documentation of this project.

Currently, at the page [Core Concepts > Model Basics > DataTypes](https://sequelize.org/docs/v6/core-concepts/model-basics/#data-types), the link leading to the [built-in data types page](https://github.com/sequelize/sequelize/blob/main/src/data-types.ts) still holds the old JS version so that this actually gets you to a [404 not found page](https://github.com/sequelize/sequelize/blob/main/src/data-types.js).

> Every column you define in your model must have a data type. Sequelize provides [a lot of built-in data types](https://github.com/sequelize/sequelize/blob/main/src/data-types.js).

### What was unclear/insufficient/not covered in the documentation
I reckon the issue sequelize/sequelize#14505 has not been reflected here, although this is a single sentence so it is easy to be looked over.

### If possible: Provide some suggestion on how we can enhance the docs
Changing the link from ".../src/data-types.js" to ".../src/data-types.ts" should be fine.

**Comment by WikiRik** [comment]
Thanks for letting us know! I've updated the page to direct to our `v6` branch which still has that file.
