### ISSUE TITLE
Redirect to the same page when changing versions

### ISSUE THREAD

**Issue by fzn0x** [sequelize/website#39]
I notice that if we change the versions for example from v6 to v7, the page will redirect to /version/, I would suggest to redirect to the same page to increase user experience.

I don't think there's any differences on menu to effectively apply this.

Your thoughts? @sdepold @ephys @WikiRik

**Comment by sdepold** [comment]
Just to have that pointed out: new.sequelizejs.com is still the gh pages version on of the page

**Comment by fzn0x** [comment]
Should be fixed on sequelize.org
