### ISSUE TITLE
Getting Started with TypeScript

### ISSUE THREAD

**Issue by Martin-Narvar** [sequelize/website#476]
## Issue Description

I just started using Sequelize for the first time, and my application is written in typeScript.
I found the getting started guide difficult to adapt to the TypeScript use case, had several false starts and had to rewrite my code a couple of times before finding an approach that works reasonably well..

I think it would be super helpful to have a Getting Started With TypeScript section in the documentation.

### What was unclear/insufficient/not covered in the documentation

Hard to get started with TypeScript.

### If possible: Provide some suggestion on how we can enhance the docs

The two main options for TypeScript seem to be https://sequelize.org/docs/v6/core-concepts/model-basics/#extending-model or https://www.npmjs.com/package/sequelize-typescript but neither option works perfectly. Maybe there are other options that I have not discovered yet.

Is there an official recommended approach to using Sequelize with TypeScript?

**Comment by ephys** [comment]
Closing as the documentation for [Sequelize 7](https://sequelize.org/docs/v7/) has been merged, and features TypeScript heavily
