### ISSUE TITLE
New page/section for "Querying by associations"

### ISSUE THREAD

**Issue by mltsy** [sequelize/website#533]
## Issue Description

I searched and experimented for hours before discovering the "nested column syntax" for including a where clause from a nested/joined table.  It was hard to find because it's in the section about eager loading (which is not at all related to what I was trying to do - I don't even need the related data returned, I just needed to filter by it).

I admit this was partly due to my laziness (AKA lack of interest in reading through pages of docs that were not related to what I needed to know), because I did find the "Eager Loading" page fairly early on, but backed out of it as most of it seemed to be focused on how to include or not include data from the associated models (i.e. eager loading!), and the part I needed (which is not actually strictly related to eager loading) was buried somewhere in the middle.

### What was unclear/insufficient/not covered in the documentation

The concepts were covered very well, but not discoverable for me, being nested under "Eager Loading"

### If possible: Provide some suggestion on how we can enhance the docs

I have two simple ideas (either of which would improve discoverability IMO):
1. Rename the "Eager Loading" section "Querying with Associations"
    - this better encompasses all that is covered in this section, and while that may sound like it's the same thing as "eager loading", eager loading is only one aspect of Querying with associations
2. Create a new section for "Filtering by associations" that would include just the sections about filtering queries by joined tables.

**Comment by WikiRik** [comment]
We've rewritten a big part of the documentation for v7. Does that documentation implement your suggestions in a good enough way?

**Comment by mltsy** [comment]
Oh, sho' nuf does! https://github.com/sequelize/website/blob/7f518768ce0e2a266a8d1e80422feb006a1c11ec/docs/querying/select-in-depth.md?plain=1#L504

I love it - thank you for pointing this out 😄 🙏   (Were these just published??  I don't know how to tell)

**Comment by ephys** [comment]
Yes, this was released about a month ago (https://github.com/sequelize/website/pull/330)
