### ISSUE TITLE
Create a redirect for 

### ISSUE THREAD

**Issue by Pomax** [sequelize/website#555]
## Issue Description

If you search google for `sequelize upgrade to 5`, you find no results, other than a stackoverflow answer that points out that https://sequelize.org/v5/manual/upgrade-to-v5.html exists. However, if  you search for `sequelize upgrade to 6` google immediately finds https://sequelize.org/docs/v6/other-topics/upgrade/

A normal dev would go "let me just replace the 6 in that URL with a 5" and expect to find the 4-to-5 documentation, so it would _super_ useful if https://sequelize.org/docs/v5/other-topics/upgrade/ existed and either redirected to https://sequelize.org/v5/manual/upgrade-to-v5.html, or better, be the source of truth with https://sequelize.org/v5/manual/upgrade-to-v5.html redirecting to the new URL instead.

**Comment by Pomax** [comment]
Given the number of projects I'm already contributing to, I'm not going to have the time to learn another codebase, someone who actually works on sequelize can get that PR written way faster, and better, than I would be able to.

**Comment by WikiRik** [comment]
After merging #556 https://sequelize.org/docs/v5/other-topics/upgrade/ will redirect to https://sequelize.org/v5/manual/upgrade-to-v5.html
