### ISSUE TITLE
Transaction readOnly option is not documented.

### ISSUE THREAD

**Issue by Parsonswy** [sequelize/website#562]
### What was unclear/insufficient/not covered in the documentation

Hello 👋.

Digging through the transaction code, [I noticed there is a `readOnly` option](https://github.com/sequelize/sequelize/blob/v6/src/transaction.js#L118C35-L118C35) to control whether the transaction is started on a primary or a replica, but it is not documented or in the Typescript definitions. Should it be?

### If possible: Provide some suggestion on how we can enhance the docs

Add `readOnly` to the list of documented parameters for the transaction constructor/`sequelize.transaction()`.

### Additional context

The option is not in the Typescript definitions either. This is from the Sequelize `v6` branch.

**Comment by WikiRik** [comment]
It's documented in the v7 docs; https://sequelize.org/docs/v7/querying/transactions/#read-replication and https://sequelize.org/api/v7/interfaces/_sequelize_core.index.transactionoptions#readOnly

Feel free to open a PR for adding it to the v6 docs
