### ISSUE TITLE
Redirect docs.sequelizejs.com

### ISSUE THREAD

**Issue by ephys** [sequelize/website#58]
https://docs.sequelizejs.com/ was used at one point to host the documentation. Can we redirect it to the new website?

I think they should be redirect to /v3:

http://docs.sequelizejs.com/en/latest/docs/raw-queries/
should redirect to
https://sequelize.org/v3/docs/raw-queries/

**Comment by sdepold** [comment]
Hmmmm tricky. I can redirect docs. To .org/v3 ?

**Comment by ephys** [comment]
I think this can be solved by redirecting the domain name first, keeping the path identical, then redirect `/en/latest/*` to /v3/:splat` in netlify

**Comment by sdepold** [comment]
So I created now the following redirect:

docs.sequelizejs.com => sequelize.org/v3

**Comment by ephys** [comment]
It looks like it's redirecting to sequelize.org/master which then redirects to v6
