### ISSUE TITLE
Broken example code on Raw SQL page

### ISSUE THREAD

**Issue by Hornwitser** [sequelize/website#634]
## Issue Description

The first example on the [Raw SQL (literals)](https://sequelize.org/docs/v7/querying/raw-queries/#writing-raw-sql) page show the following code

```js
import { sql } from '@sequelize/core';

const id = 5;

await sequelize.query(sql`SELECT * FROM users WHERE id = ${id}`);
```
But when run against `@sequelize/core@7.0.0-alpha.33` it throws the following error

```
node_modules/@sequelize/core/lib/sequelize.js:555
      throw new TypeError('"sql" cannot be an object. Pass a string instead, and pass bind and replacement parameters through the "options" parameter');
            ^

TypeError: "sql" cannot be an object. Pass a string instead, and pass bind and replacement parameters through the "options" parameter
    at Sequelize.query (node_modules/@sequelize/core/lib/sequelize.js:555:13)
    at test.js
```

### What was unclear/insufficient/not covered in the documentation

The example code seems to be out of date due to the breaking change in sequelize/sequelize#14447, but it's not clear what it's supposed to be replaced with. At first I thought the entire page was out of date due to this.

### If possible: Provide some suggestion on how we can enhance the docs

It would be nice if the example code was updated with the correct way to use `sequelize.query()`.

**Comment by WikiRik** [comment]
```ts
await sequelize.query(sql`SELECT * FROM users WHERE id = 5`);
```
works, but I'm not sure if we should just replace the example with that. I'll leave this open for @ephys to comment on

**Comment by Hornwitser** [comment]
Wouldn't it make more sense to replace it with a bind parameter? i.e.:

```js
const id = 5;

await sequelize.query('SELECT * FROM users WHERE id = $1', { bind: [id] });
```

Preceding text would then have be changed to not reference `sql`.

**Comment by ephys** [comment]
This is an issue with `sequelize.query`, not the documentation. `sequelize.query` should support the `sql` tag as its auto-escaping capabilities makes using `query` safer

**Comment by Hornwitser** [comment]
Could the documentation perhaps have a note saying this is a planned feature and link to an issue tracking it? It's very useful to know.
