### ISSUE TITLE
Slack link on web site is expired

### ISSUE THREAD

**Issue by dscottboggs** [sequelize/website#709]
## Issue Description

Clicking the "**Slack ↗️**" link on the top-left of the web page brings you to [this page](https://sequelize.slack.com/join/shared_invite/zt-23cgoa4v7-wj_46zFMPaFmXQxsZXvcOg#/shared-invite/error)

![Screenshot: Slack: this link is no longer active](https://github.com/sequelize/website/assets/7088510/889d9cf2-48cd-4fab-891e-afab7c6ce177)

**Comment by WikiRik** [comment]
It seems that Slack deactives links after 400 people used it, even if you set it to never expire. But it doesn't inform you when the 400 people have been reached. Thanks for informing us of this, I'll open a PR to fix this
