### ISSUE TITLE
Optional doesn't exist in Sequelize 7, but mentioned in documentation

### ISSUE THREAD

**Issue by pocketarc** [sequelize/website#716]
## Issue Description

I'm working on a greenfield Sequelize 7 project, and the documentation mentions the use of `Optional` in "Manual Attribute Typing", to specify which attributes are CreationOptional.

https://sequelize.org/docs/v7/models/model-typing/#manual-attribute-typing

### What was unclear/insufficient/not covered in the documentation

There doesn't seem to be an Optional in Sequelize 7. Is it supposed to be something else? 

Edit: From looking at the code, it looks like it could just be `Omit<UserAttributes, 'id'>` . I'm still looking into it though.

### If possible: Provide some suggestion on how we can enhance the docs

The documentation could be clearer about manual attribute typing. If anyone knows the right way to handle it, I'd be happy to work on a PR to update the documentation wherever needed.

**Comment by ephys** [comment]
Thank you for letting us know!

It was renamed to `PartialBy` and is now available in the newly published `@sequelize/util` package instead of `@sequelize/core`. You can also use `SetOptional` from `type-fest` for the same outcome

**Comment by pocketarc** [comment]
@ephys By the way, I've now raised a PR to update the documentation.

**Comment by ephys** [comment]
Thank you :)
