### ISSUE TITLE
Support windows authentication for MSSQL Sever

### ISSUE THREAD

**Issue by zeagord** [sequelize/website#730]
**Is your feature request related to a problem? Please describe.**

Current sequelize module doesn't support sql server windows authentication which is preventing the usage in several environments.

**Describe the solution you'd like**
Option to use Windows Authentication in some environments

**Why should this be in Sequelize**
Short explanation why this should be part of Sequelize rather than a separate package.

**Describe alternatives you've considered**
Tried the module `sequelize-msnodesqlv8` but it is not maintained anymore or works for me

**Comment by LtFinTutuola** [comment]
> > sorry for the noob comment, but is there a way to rely on the tedious connection for this? i can connect to MSSQL using windows authentication with tedious using this connection config
> > ```
> > var Connection = require('tedious').Connection
> > var config = {
> >   server: 'SERVER',
> >   authentication: {
> >     type: 'ntlm',
> >     options: {
> >       domain: 'DOMAIN',
> >       userName: 'USER',
> >       password: 'PASS'
> >     }
> >   },
> >   options: {
> >     encrypt: true,
> >     database: 'DB_NAME'
> >   }
> > }
> > var connection = new Connection(config)
> > ```
> 
> ```
> const config = {
>   host: process.env.DB_SERVER,
>   dialect: 'mssql',
>   dialectOptions: {
>     authentication: {
>       type: 'ntlm',
>       options: {
>         domain: process.env.DB_DOMAIN,
>         userName: process.env.DB_USERNAME,
>         password: process.env.DB_PASSWORD,
>       },
>     },
>     options: {
>       instanceName: process.env.DB_INSTANCE,
>     }
>   },
> };
> 
> const sequelize = new Sequelize(
>   process.env.DB_NAME,
>   null,
>   null,
>   config,
> );
> ```
> 
> As per well-hidden here, https://github.com/vishwasjois/sequelize/blob/988e754c6eef323b1a9dc11f5bee3fb535579da8/docs/upgrade-to-v5.md#dialect-specific

I broke my head on this for half a day... You are a fucking HOLY man, bro!

**Comment by ylerjen** [comment]
> @troyfitzwater were you able to find how to use Windows Authentication (or an alternative, I do not think you can use Windows Authentication in linux) through trusted connection (not having to provide the password) in Linux?

This should be possible by generating a keytab. More info about this is available on MS official documentation:
https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-ver16

**Comment by ephys** [comment]
I'll close this issue because authentication options are now documented in https://sequelize.org/docs/v7/databases/mssql/
