### ISSUE TITLE
No list of available dialectOptions 

### ISSUE THREAD

**Issue by remjx** [sequelize/website#731]
## What was unclear/insufficient/not covered in the documentation

This page seems to be the only mention of dialectOptions http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html

It only includes a few examples of dialectOptions, and no descriptions of them. I know there are more that are not mentioned e.g. `decimalNumbers`. 

### If possible: Provide some suggestion how we can enhance the docs

List all possible dialectOptions by dialect.

**Comment by ephys** [comment]
This part of the website now lists all available dialects & their options: https://sequelize.org/docs/v7/category/databases/
